### ISSUE TITLE
support headers with underlines instead of leading hashes

### ISSUE THREAD

**Issue by scrooloose** [mzlogin/vim-markdown-toc#11]
It would be cool if this style of heading was supported:

```
A heading
=========

A subheading
--------------
```

I generally prefer this style for simple documents.

**Comment by mzlogin** [comment]
Useful advice. I will try to do some work around it.

Thanks!

**Comment by mzlogin** [comment]
A workaround has been committed.

You can update the plugin and try it now. 😄

**Comment by scrooloose** [comment]
This looks great :-D I will use this at work this week and report any bugs.
