### ISSUE TITLE
If the head is a link, the toc generated is not expected.

### ISSUE THREAD

**Issue by liuchengxu** [mzlogin/vim-markdown-toc#13]
For example :

```
### [vim-airline](https://github.com/vim-airline/vim-airline)
```
then the generated toc is : 

```
### 	* [[vim-airline](https://github.com/vim-airline/vim-airline)](#vim-airlinehttpsgithubcomvim-airlinevim-airline)
```
This will lead to a direct visit to the link. However, I hope it lead to the right position in the current page.

So, what I expected is : 
```
### * [vim-airline](#vim-airline)
```

**Comment by mzlogin** [comment]
Yes, that a bug. I will try to fix it.

Thanks for reporting! 😄

**Comment by mzlogin** [comment]
Fixed, please update and try again.

Your feedback is excepted, thanks a lot! 😆
