### ISSUE TITLE
Enhancement: add line numbers for easy navigation from toc to body

### ISSUE THREAD

**Issue by assaf758** [mzlogin/vim-markdown-toc#18]

**Comment by mzlogin** [comment]
I have no idea for how to implement this graceful.

For easy navigation in Markdown files, [Voom](https://github.com/vim-scripts/VOoM) or [solution by tagbar](http://mazhuang.org/2016/08/03/add-outline-for-markdown-in-vim/) may better choices.

**Comment by assaf758** [comment]
thx
