### ISSUE TITLE
TOC links with non ascii characters

### ISSUE THREAD

**Issue by 1978ajot** [mzlogin/vim-markdown-toc#21]
I'm using pandoc to convert my markdown files to HTML format. When using `:GenTocRedcarpet` command, generated TOC links looks like:
`[Wstępna konfiguracja karty](#wstępna-konfiguracja-karty)`

Pandoc creates `<h>` tags that looks like:
`<h2 id="wstepna-konfiguracja-karty">Wstępna konfiguracja karty</h2>`

As you see, there are no letters other than ascii characters inside `id` attribute.

Is it possible to to pass link part of TOC through command like `iconv -t ascii//TRANSLIT`, so letters like `ę`, `ą`, `ś` will be replaced by `e`, `a`, `s`?

Regards,

Andrzej.

**Comment by mzlogin** [comment]
<https://github.com/jgm/pandoc/wiki/Pandoc-Tricks#using-markdown-templates>

This may helpful to solve your problem, use Pandoc's feature to get your goal achieve may better solution.

**Comment by 1978ajot** [comment]
Thank you for your advice. That's not exactly what I need, but with a little bit of scripting it is quite usable solution for me.
