### ISSUE TITLE
Add option to enable for different filetypes

### ISSUE THREAD

**Issue by caedn** [mzlogin/vim-markdown-toc#22]
I'm using vimwiki with markdown syntax. 

To generate the html I'm using [livedown](https://github.com/shime/livedown) which itself uses [marked](https://github.com/chjj/marked). 

That works great with using `:GenTocRedcarpet`. The only problem is that I have to run `:set ft=markdown` so that this plug loads and then run `:set ft=vimwiki` to use all the vimwiki features. 

Once I've done that I can use `:UpdateToc` and it works great. Long story short I'd love to have option that lets me load this plugin for a different filetype than markdown.

**Comment by mzlogin** [comment]
To use vimwiki files with Markdown, you can just change you wiki files' suffix name to one of `md,mdown,mkd,mkdn,markdown,mdwn`. Then you can use all the vimwiki features and vim-markdown-toc at the same time. Settings just like this:

```viml
let g:vimwiki_list = [{
            \ 'path'    :   '~/vimwiki/',
            \ 'syntax'  :   'markdown',
            \ 'ext'     :   '.mkd'
}]
```

**Comment by caedn** [comment]
Ha, you are right. I've have just been using `'syntax' : 'markdown',` in `g:vimwiki_list`. I have totally missed `'ext': '.mkd'` but it does exactly what you describe. Thank you.
