### ISSUE TITLE
How to remove TOC ?

### ISSUE THREAD

**Issue by ashutoshmjain** [mzlogin/vim-markdown-toc#28]
I generated the TOC and its working well  .. For now I want to remove it till I finish formatting t he document and then regenerate the TOC  .. Is there a command for removing the TOC  ? 

Thanks in advance

**Comment by mzlogin** [comment]
There's no command already have to remove TOC before your issue. So I add one just now. 😄 

So please update this plugin to newest version, and you can do it by command `:RemoveToc`.

btw: TOC will auto update on save by default, why do you want to remove the TOC and regenerate it later?
