### ISSUE TITLE
1.1 带点的标题无法生成正确的目录

### ISSUE THREAD

**Issue by BillWang139967** [mzlogin/vim-markdown-toc#29]
1.1 使用此插件   生成的目录为·`[1.1](#1.1)`

正确的应该是`[1.1](#11)`

**Comment by mzlogin** [comment]
您好，请问您使用的命令是 `:GenTocGFM` 还是 `:GenTocRedcarpet` 呢？

我在我的环境试了一下，`:GenTocGFM` 生成的是 `[1.1](#11)`，`:GenTocRedcarpet` 生成的是 `[1.1](#1-1)`，可以麻烦您确认一下是否使用插件最新版本，以及提供一段您的测试文本么？

**Comment by BillWang139967** [comment]
1 more line
Error detected while processing function <SNR>28_GenToc..<SNR>28_GetHeadingLink..<SNR>28_GetHeadingLinkGFM:
line    4:
E16: Invalid range
1 more line
1 more line
1 more line

**Comment by BillWang139967** [comment]
升级了下vim版本好了，原先版本是
```
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)
```
在vim 7.2的版本上会有问题 @mzlogin

**Comment by mzlogin** [comment]
@BillWang139967 

收到~感谢反馈。我稍后在 Vim 7.2 试一下，考虑是否做兼容。

**Comment by mzlogin** [comment]
测试了一下，在 Vim 7.4+ 版本才能正常使用，原因是在 7.4 引入新的正则引擎之前，旧的正则引擎无法识别表达式里的 `\u4e00-\u9fbf` 这种形式，会报 `E16: Invalid range`，在 #19 曾经遇到过这个问题。目前暂时没找到有效的适用低版本的写法，我先将适用版本标为 7.4+ 吧，如果你有这种情况的解决方案欢迎提供~ 😄

**Comment by BillWang139967** [comment]
好的，:)
