### ISSUE TITLE
Add a black line before toc

### ISSUE THREAD

**Issue by wsdjeg** [mzlogin/vim-markdown-toc#31]
in the latest version of this plugin, the toc is looks like

```markdown
<!-- vim-markdown-toc GFM -->
* [安装](#安装)
* [更新](#更新)
* [文档](#文档)
    * [核心思想](#核心思想)
        * [记忆辅助](#记忆辅助)
        * [可视化交互](#可视化交互)
        * [一致性](#一致性)
        * [社区驱动](#社区驱动)

<!-- vim-markdown-toc -->
```

but, after use remark to formate markdown file, it looks like:

```markdown
<!-- vim-markdown-toc GFM -->

- [安装](#安装)
- [更新](#更新)
- [文档](#文档)
  - [核心思想](#核心思想)
    - [记忆辅助](#记忆辅助)
    - [可视化交互](#可视化交互)
    - [一致性](#一致性)
    - [社区驱动](#社区驱动)

<!-- vim-markdown-toc -->
```

I think it looks better, maybe you do not need to change the list item from `*` to `-`, but an option can be added for it.

for more info see https://github.com/wooorm/remark/tree/master/packages/remark-stringify#optionslistitemindent

and I will try to send a PR for this issue, and the previous issue I have opened.

**Comment by wsdjeg** [comment]
sorry, I do not see `g:vmt_cycle_list_item_markers`, this option looks better.

**Comment by mzlogin** [comment]
OK, thx. 😄
