### ISSUE TITLE
Doesn't find if the fence is on the first line but not first column

### ISSUE THREAD

**Issue by lilydjwg** [mzlogin/vim-markdown-toc#43]

**Comment by mzlogin** [comment]
Not really understand. In my environment, toc fence on the first line can work fine.

like this:

```
<!-- vim-markdown-toc GFM -->

* [你好世界](#你好世界)
* [hello](#hello)
* [world](#world)
* [???](#)

<!-- vim-markdown-toc -->

## 你好世界

## hello

## world

## ???
```

do you mean heading in the first line not contained in the generated toc?

if not, can you give a example for issue?

**Comment by lilydjwg** [comment]
Oh, it only fails when the cursor isn't on the first column. Then it'll be simple to fix.

**Comment by mzlogin** [comment]
Yes, that would be a bug when `set nostartofline`, thx!
