### ISSUE TITLE
Can not navigate to the content when click title

### ISSUE THREAD

**Issue by bdgong** [mzlogin/vim-markdown-toc#47]
Use `Vundle` to manage my vim plugins.  Use `vim-instant-markdown` to preview markdown. Since I know `vim-markdown-toc` is a good plugin then just have a try, but I can only generate ToC with `vim-markdown-toc`, click any title, just can not navigate to the content?

**Comment by bdgong** [comment]
Already have a similar issue, I should close it.

**Comment by mzlogin** [comment]
Yes, please ref <https://github.com/mzlogin/vim-markdown-toc/issues/6#issuecomment-211185759>

**Comment by bdgong** [comment]
I change to `iamcco/markdown-preview`, now I can navigate between level 2 headers '##', but not lower headers, like '###'.

**Comment by mzlogin** [comment]
I just test for it, in my environment I can navigate between level 2/3/4/5... headers well. Could you provide a markdown content snippets to reproduce your problem?

ps: `iamcco/markdown-preview` use https://github.com/markedjs/marked as its Markdown Parser, the support for it has not been tested.

**Comment by bdgong** [comment]
Anyway, which vim plugin you use to preview markdown?

**Comment by mzlogin** [comment]
![image](https://user-images.githubusercontent.com/1646590/43242559-54ec88b4-90d4-11e8-8992-a86399eab115.png)

Just use Chrome devtools, the `id` value is anchor.

anchors generated for header `2.4 Guarding State with Locks`:

* iamcco/markdown-preview: `2.4-guarding-state-with-locks`

* gitee: `24-guarding-state-with-locks`

* Redcarpet: `2-4-guarding-state-with-locks`

They all different from others. So I give up to find a tool which can preview markdown with toc links are right. I just confirm styles.

ps: If you want to upload markdown to gitee, use command `:GenTocGitLab` may better.

**Comment by bdgong** [comment]
OK, thank you very much~

**Comment by mzlogin** [comment]
Sadly you can't generate toc once, work well in all of markdown preview, GitHub, Gitee, or even any two of them.

If you just want to use toc in markdown preview, maybe we can add a command `:GenTocMarked` for iamcco/markdown-preview, like `:GenTocGFM` for GitHub, `:GenTocGitLab` for GitLab. You can ref https://github.com/mzlogin/vim-markdown-toc/blob/a6e227023f405a7c39590a8aaf0d54dde5614a2e/ftplugin/markdown.vim#L126 for how to implement.

**Comment by bdgong** [comment]
That's what I need, thank you

**Comment by mzlogin** [comment]
You are welcome. And...welcome to PR for this if you implement it. 😆
