### ISSUE TITLE
Start and End Level [feature request]

### ISSUE THREAD

**Issue by ndaman** [mzlogin/vim-markdown-toc#56]
It would be cool if there was an option to set to define the minimum and maximum levels in the table of contents.

**Comment by ndaman** [comment]
I'm new to git and contributions, but I went ahead and (locally) made changes to add a few variables

vmt_link defaults to 1 and defines whether or not you want the toc to generate a link
vmt_min_level defaults to 1 and defines the minimum header level you want included in your toc
vmt_max_level defaults to 6 and defines the maximum header level you want included in the toc

I assume a pull request is the way to go about officially submitting my work for you to review and potentially include?

**Comment by miruohotspring** [comment]
It looks like this issue can be closed: #58

**Comment by mzlogin** [comment]
Yes, thank you guys.
