### ISSUE TITLE
Option to use tabs rather than spaces?

### ISSUE THREAD

**Issue by andrewferrier** [mzlogin/vim-markdown-toc#59]
It seems that `vim-markdown-toc` always uses hard tabs to indent subsections within a table of contents, even if `expandtab` is turned on in vim (and thus the user prefers spaces). It would more be elegant and fit in better with the users' other preferences if it honored that option.

Thanks for your fine work on this plugin!

**Comment by andrewferrier** [comment]
My apologies, this was wrong. It does honor `expandtab`, another plugin I has was misbehaving. Sorry!

**Comment by mzlogin** [comment]
It doesn't matter.
