### ISSUE TITLE
please add a new feature of updating existing toc

### ISSUE THREAD

**Issue by hitzhangjie** [mzlogin/vim-markdown-toc#6]
First of all, thanks for your good work, it's very convenient to generate toc now. If you add a new feature like updating existing toc when triggering some hotkeys, it would be more useful. Is it right?
I have no vim script programming experience, but I think this is a good idea for some document which contains a long table of contents. If you add a updating-toc feature, we don't have to delete existing toc again. And I think inserting toc before the document is finished is useful too, because it can help us navigate the document.
So I think add a updating-toc feature is very useful. Thanks!

**Comment by hitzhangjie** [comment]
I have another question, 'toc' generated by your plugin, I cannot used it for navigate in documents, I used 'instant-markdown' for realtime preview. Do they the two plugins conflict with each other?

**Comment by mzlogin** [comment]
@hitzhangjie For your second question, it seems 'instant-markdown' use [CommonMark](https://github.com/jgm/CommonMark) as it's Markdown parser, CommonMark does not add anchor to headings automatic default, and TOC link relyon this feature. Maybe you can find some options in these plugins to turn on this.

If you find the realtime preview page's headings have anchor with them, could you provider a demo generated html file to me for analyze? Thanks.

**Comment by mzlogin** [comment]
@hitzhangjie Updating existing toc is a good idea, I'll work on it when I got some free time.

**Comment by sunaku** [comment]
Here is how I do this from Vim's command mode:

```vim
:/\V<!-- vim-markdown-toc \w\+ -->/,/\V<!-- vim-markdown-toc -->/d|execute 'normal! k'|GenTocGFM
```

You can replace `GenTocGFM` with `GenTocRedcarpet` as the last word of the command line too.

**Comment by sunaku** [comment]
Oops, it seems there is already a `UpdateToc` command provided by this plugin. :santa:

**Comment by mzlogin** [comment]
@sunaku Yeah, I updated the code yesterday to add `:UpdateToc` command and a feature of auto update toc on save, but have not update the README doc. Sorry about that, I'll do it soon. Your command mode command above is very concisely, thanks.

@hitzhangjie You can use `:UpdateToc` command to update existing toc generated by this plugin now, and by default, the toc will auto update when save, you also can add `let g:vmt_auto_update_on_save = 0` to your vimrc file to close this feature.

**Comment by sunaku** [comment]
Awesome! :sparkles: Auto-update on save sounds great! :+1: Thanks @mzlogin. :santa:
