### ISSUE TITLE
Wrong parsing in comment

### ISSUE THREAD

**Issue by KyleJeong** [mzlogin/vim-markdown-toc#69]
I made this kind of python syntax highlighting codes in a markdown file.

Then this plugin thinks that the "# mod1.py" is  a heading level 1.
Can you skip that kind of syntax highlighting blocks?

~~~ python
# mod1.py
def add(a, b):
    return a + b


def sub(a, b):
    return a - b
~~~

**Comment by mzlogin** [comment]
OK, I'll look at it later.

Before this plugin is updated, you can use this kind of syntax as a workaround:

``````
```python
print('hello')
```
``````

**Comment by KyleJeong** [comment]
back-quote is working. Thank you for the quick feedback.

**Comment by mzlogin** [comment]
Fixed! You can try ```~~~``` syntax now.
