### ISSUE TITLE
目录不再缩进显示了

### ISSUE THREAD

**Issue by YHYJ** [mzlogin/vim-markdown-toc#73]
![深度截图_选择区域_20201019162540](https://user-images.githubusercontent.com/21995281/96420216-cb5fa680-1227-11eb-8be8-5fffbe5750be.png)

如图，之前都是能够缩进显示的，不知道怎么最近都不能缩进了

**Comment by mzlogin** [comment]
我在本地试了下，用你的这段文本是可以正常缩进的。

你排查下以下几点吧：

用 Vim 打开以上文件

1. 检查你的配置文件里有没有手动设置 `g:vmt_list_indent_text` 为空；
2. 执行 `:echo &shiftwidth` 看输出。

比较怀疑是 shiftwidth 被设置为 0 了。

**Comment by YHYJ** [comment]
1. 没有`g:vmt_list_indent_text`这个配置项，help也找不到它
2. shiftwidth值是2

**Comment by YHYJ** [comment]
我看markdown.vim文件里设置了好些变量，但这些变量我在vim里都找不到怎么

**Comment by mzlogin** [comment]
> 我看markdown.vim文件里设置了好些变量，但这些变量我在vim里都找不到怎么

你说的找不到是指 help 找不到它么？可能是因为……我没有写说明文档 😿

**Comment by YHYJ** [comment]
啊～～～原来如此，关了关了
