### ISSUE TITLE
Configuration option missing from README.md

### ISSUE THREAD

**Issue by danisztls** [mzlogin/vim-markdown-toc#74]
I wanted to indent table item with 2 spaces instead of 4 and found an option on script that does that and is missing in the documentation.

Change

`let g:vmt_list_indent_text = ''`

To

`let g:vmt_list_indent_text = '  '`

**Comment by oalders** [comment]
I was also looking for this option. Thanks for raising the issue @danisztls. That fixed it for me. It would be great if this were documented.

**Comment by mzlogin** [comment]
Thanks guys, the docs has been updated.

**Comment by oalders** [comment]
Looks great, @mzlogin. Thanks! I guess you can close this issue. Thank you for sharing your work. I love this plugin. 😄

**Comment by mzlogin** [comment]
OK, thank you as well.
