### ISSUE TITLE
插件无法工作

### ISSUE THREAD

**Issue by qiyinhe** [mzlogin/vim-markdown-toc#78]
系统：windows10
vim版本：vim 8.2
错误提示：输入:GenTocGFM后提示 E492：不是编辑器的命令： GentocGFM
_vimrc: 
set rtp+=$VIM\vimfiles\bundle\Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-surround'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'zxqfl/tabnine-vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'mzlogin/vim-markdown-toc'
Plugin 'iamcco/markdown-preview.vim'
call vundle#end()

**Comment by mzlogin** [comment]
我在本地尝试了下，参考 Vundle 插件的文档：https://github.com/VundleVim/Vundle.vim#quick-start

在用 Vundle 管理插件时，配置文件里 `call vundle#end()` 后面需要有 `filetype plugin indent on`，我本地尝试的结果是如果不加这一行，就会提示找不到命令，加上之后插件正常工作。

**Comment by qiyinhe** [comment]
> 我在本地尝试了下，参考 Vundle 插件的文档：https://github.com/VundleVim/Vundle.vim#quick-start
> 
> 在用 Vundle 管理插件时，配置文件里 `call vundle#end()` 后面需要有 `filetype plugin indent on`，我本地尝试的结果是如果不加这一行，就会提示找不到命令，加上之后插件正常工作。

**Comment by qiyinhe** [comment]
可行，已解决，非常感谢！

**Comment by mzlogin** [comment]
不客气～😃
