### ISSUE TITLE
为什么toc生成的跳转会有问题？？而且生成的格式也有问题

### ISSUE THREAD

**Issue by EdwardWong1994** [mzlogin/vim-markdown-toc#85]
您好，今天刚接触到这个插件，想咨询一些问题，为什么生成的`toc`目录点击链接却无法跳转。

<img width="486" alt="image" src="https://github.com/mzlogin/vim-markdown-toc/assets/96438179/81ca6c91-1430-4d3a-9c87-1913d74fb72b">

还有一个问题就是不清楚为什么`1.specimen`和后面的`1.2.1`之间为什么间隔这么大？？  请问有人知道这是怎么回事吗？？

**Comment by mzlogin** [comment]
用的什么 Markdown 解析引擎？

两级目录显示间隔大是解析引擎渲染的样式问题，插件只负责生成文本，不涉及渲染。

**Comment by EdwardWong1994** [comment]
> 用的什么 Markdown 解析引擎？
> 
> 两级目录显示间隔大是解析引擎渲染的样式问题，插件只负责生成文本，不涉及渲染。

我使用 的是`markdown-preview`插件， 请问怎么解决这个问题呢

**Comment by mzlogin** [comment]
markdown-preview 这个插件我也用，它引用的 markdown-it 作为解析引擎，我这边试了下用 `:GenTocMarked` 生成的 toc 基本都能正常跳转。还有就是您得考虑下，这个文档最终是打算发布到哪里的，最需要考虑的是目标平台使用的是什么解析引擎，然后使用对应的命令去生成 toc。如果只是需要 markdown-preview 里查看，那其实可以不使用命令生成，使用 markdown-preivew 里的 toc 功能就好，参考 <https://github.com/iamcco/markdown-preview.nvim#custom-examples>

第二个问题，markdown-preview 插件支持自定义修改预览的样式，比如我自定义了一个 css 文件：<https://github.com/mzlogin/config-files/blob/main/_vimrc#L465>

**Comment by mzlogin** [comment]
这个问题我先关闭了哈～如果还有问题，欢迎 reopen 或者开新 Issue 继续讨论。
